package android.emcom;

import android.emcom.SmartcareInfos.SmartcareBaseInfo;

public class GameInfo extends SmartcareBaseInfo {
    private static final String TAG = "GameInfo";
    public String appName;
    public int battleDur;
    public short battleRttAvg;
    public short battleRttL1Dur;
    public short battleRttL2Dur;
    public short battleRttL3Dur;
    public short battleRttL4Dur;
    public short battleRttL5Dur;
    public short battleRttL6Dur;
    public short battleRttL7Dur;
    public short battleRttL8Dur;
    public String cellId;
    public byte connDropFlg;
    public int gameEndTime;
    public int gameLoadLat;
    public int gameLoadThrput;
    public int gameStartDate;
    public int gameStartTime;
    public String hostName;
    public byte initPrbRoute;
    public short mcc;
    public short mnc;
    public byte networkType;
    public short policyMode;
    public int policyStartCond;
    public int policySwCnt;
    public int policyType;
    public short radioL1Dur;
    public short radioL2Dur;
    public short radioL3Dur;
    public short radioL4Dur;
    public short radioL5Dur;
    public int radioSnr;
    public byte radioSq;
    public byte radioSs;
    public int selfRoleLoadLat;
    public byte selfRoleLoadSuccFlg;
    public byte succFlg;
    public short swB2BCnt;
    public short swB2GCnt;
    public short swG2BCnt;
    public short swG2GCnt;
    public String techCode;
    public byte type;
    public String wlanBssid;
    public short wlanL1Dur;
    public short wlanL2Dur;
    public short wlanL3Dur;
    public short wlanL4Dur;
    public byte wlanSs;
    public String wlanSsid;

    public GameInfo() {
        init();
    }

    public void addToInfos(SmartcareInfos cis) {
        super.addToInfos(cis);
        cis.gameInfo = this;
    }

    public final void copyFrom(GameInfo o) {
        this.hostName = o.hostName;
        this.gameStartDate = o.gameStartDate;
        this.gameStartTime = o.gameStartTime;
        this.gameEndTime = o.gameEndTime;
        this.mcc = o.mcc;
        this.mnc = o.mnc;
        this.networkType = o.networkType;
        this.cellId = o.cellId;
        this.radioSs = o.radioSs;
        this.radioSq = o.radioSq;
        this.radioSnr = o.radioSnr;
        this.radioL1Dur = o.radioL1Dur;
        this.radioL2Dur = o.radioL2Dur;
        this.radioL3Dur = o.radioL3Dur;
        this.radioL4Dur = o.radioL4Dur;
        this.radioL5Dur = o.radioL5Dur;
        this.wlanSs = o.wlanSs;
        this.wlanBssid = o.wlanBssid;
        this.wlanSsid = o.wlanSsid;
        this.wlanL1Dur = o.wlanL1Dur;
        this.wlanL2Dur = o.wlanL2Dur;
        this.wlanL3Dur = o.wlanL3Dur;
        this.wlanL4Dur = o.wlanL4Dur;
        this.appName = o.appName;
        this.type = o.type;
        this.gameLoadLat = o.gameLoadLat;
        this.gameLoadThrput = o.gameLoadThrput;
        this.connDropFlg = o.connDropFlg;
        this.selfRoleLoadLat = o.selfRoleLoadLat;
        this.selfRoleLoadSuccFlg = o.selfRoleLoadSuccFlg;
        this.battleDur = o.battleDur;
        this.battleRttAvg = o.battleRttAvg;
        this.battleRttL1Dur = o.battleRttL1Dur;
        this.battleRttL2Dur = o.battleRttL2Dur;
        this.battleRttL3Dur = o.battleRttL3Dur;
        this.battleRttL4Dur = o.battleRttL4Dur;
        this.battleRttL5Dur = o.battleRttL5Dur;
        this.battleRttL6Dur = o.battleRttL6Dur;
        this.battleRttL7Dur = o.battleRttL7Dur;
        this.battleRttL8Dur = o.battleRttL8Dur;
        this.techCode = o.techCode;
        this.policyStartCond = o.policyStartCond;
        this.policyType = o.policyType;
        this.policyMode = o.policyMode;
        this.initPrbRoute = o.initPrbRoute;
        this.succFlg = o.succFlg;
        this.policySwCnt = o.policySwCnt;
        this.swB2GCnt = o.swB2GCnt;
        this.swB2BCnt = o.swB2BCnt;
        this.swG2GCnt = o.swG2GCnt;
        this.swG2BCnt = o.swG2BCnt;
    }

    private void init() {
        this.hostName = "";
        this.gameStartDate = 0;
        this.gameStartTime = 0;
        this.gameEndTime = 0;
        this.mcc = (short) 0;
        this.mnc = (short) 0;
        this.networkType = (byte) 0;
        this.cellId = "";
        this.radioSs = (byte) -1;
        this.radioSq = (byte) -1;
        this.radioSnr = -1;
        this.radioL1Dur = (short) 0;
        this.radioL2Dur = (short) 0;
        this.radioL3Dur = (short) 0;
        this.radioL4Dur = (short) 0;
        this.radioL5Dur = (short) 0;
        this.wlanSs = (byte) -1;
        this.wlanBssid = "";
        this.wlanSsid = "";
        this.wlanL1Dur = (short) 0;
        this.wlanL2Dur = (short) 0;
        this.wlanL3Dur = (short) 0;
        this.wlanL4Dur = (short) 0;
        this.appName = "";
        this.type = (byte) 0;
        this.gameLoadLat = 0;
        this.gameLoadThrput = 0;
        this.connDropFlg = (byte) 0;
        this.selfRoleLoadLat = 0;
        this.selfRoleLoadSuccFlg = (byte) -1;
        this.battleDur = 0;
        this.battleRttAvg = (short) 0;
        this.battleRttL1Dur = (short) 0;
        this.battleRttL2Dur = (short) 0;
        this.battleRttL3Dur = (short) 0;
        this.battleRttL4Dur = (short) 0;
        this.battleRttL5Dur = (short) 0;
        this.battleRttL6Dur = (short) 0;
        this.battleRttL7Dur = (short) 0;
        this.battleRttL8Dur = (short) 0;
        this.techCode = "";
        this.policyStartCond = 0;
        this.policyType = 0;
        this.policyMode = (short) 0;
        this.initPrbRoute = (byte) 0;
        this.succFlg = (byte) 0;
        this.policySwCnt = 0;
        this.swB2GCnt = (short) 0;
        this.swB2BCnt = (short) 0;
        this.swG2GCnt = (short) 0;
        this.swG2BCnt = (short) 0;
    }

    public void recycle() {
        super.recycle();
        init();
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("hash: ");
        sb.append(hashCode());
        sb.append(",StartDate: ");
        sb.append(this.gameStartDate);
        sb.append(",StartTime: ");
        sb.append(this.gameStartTime);
        sb.append(",EndTime: ");
        sb.append(this.gameEndTime);
        sb.append(",app: ");
        sb.append(this.appName);
        sb.append(",type: ");
        sb.append(this.type);
        sb.append(",gameLoadLat: ");
        sb.append(this.gameLoadLat);
        sb.append(",connDropFlg: ");
        sb.append(this.connDropFlg);
        sb.append(",selfRoleLoadLat: ");
        sb.append(this.selfRoleLoadLat);
        sb.append(",battleDur: ");
        sb.append(this.battleDur);
        sb.append(",battleRttAvg: ");
        sb.append(this.battleRttAvg);
        sb.append(",networkType: ");
        sb.append(this.networkType);
        sb.append(",radioSs: ");
        sb.append(this.radioSs);
        sb.append(",radioSnr: ");
        sb.append(this.radioSnr);
        sb.append(",wlanSs: ");
        sb.append(this.wlanSs);
        sb.append(",");
        sb.append(",techCode: ");
        sb.append(this.techCode);
        sb.append(",PolicyStartCond: ");
        sb.append(this.policyStartCond);
        sb.append(",policyType: ");
        sb.append(this.policyType);
        sb.append(",policyMode: ");
        sb.append(this.policyMode);
        sb.append(",initPrbRoute: ");
        sb.append(this.initPrbRoute);
        sb.append(",succFlg: ");
        sb.append(this.succFlg);
        sb.append(",policySwCnt: ");
        sb.append(this.policySwCnt);
        sb.append(",");
        sb.append(",swB2GCnt: ");
        sb.append(this.swB2GCnt);
        sb.append(",");
        sb.append(",swB2BCnt: ");
        sb.append(this.swB2BCnt);
        sb.append(",");
        sb.append(",swG2GCnt: ");
        sb.append(this.swG2GCnt);
        sb.append(",");
        sb.append(",swG2BCnt: ");
        sb.append(this.swG2BCnt);
        return sb.toString();
    }
}
