package com.android.server.wifi;

import java.util.Arrays;

public class WifiLinkLayerStats {
    public int beacon_rx;
    public long lostmpdu_be;
    public long lostmpdu_bk;
    public long lostmpdu_vi;
    public long lostmpdu_vo;
    public int on_time;
    public int on_time_scan;
    public long retries_be;
    public long retries_bk;
    public long retries_vi;
    public long retries_vo;
    public int rssi_mgmt;
    public int rx_time;
    public long rxmpdu_be;
    public long rxmpdu_bk;
    public long rxmpdu_vi;
    public long rxmpdu_vo;
    public long timeStampInMs;
    public int tx_time;
    public int[] tx_time_per_level;
    public long txmpdu_be;
    public long txmpdu_bk;
    public long txmpdu_vi;
    public long txmpdu_vo;

    public String toString() {
        StringBuilder sbuf = new StringBuilder();
        sbuf.append(" WifiLinkLayerStats: ");
        sbuf.append(10);
        sbuf.append(" my bss beacon rx: ");
        sbuf.append(Integer.toString(this.beacon_rx));
        sbuf.append(10);
        sbuf.append(" RSSI mgmt: ");
        sbuf.append(Integer.toString(this.rssi_mgmt));
        sbuf.append(10);
        sbuf.append(" BE : ");
        sbuf.append(" rx=");
        sbuf.append(Long.toString(this.rxmpdu_be));
        sbuf.append(" tx=");
        sbuf.append(Long.toString(this.txmpdu_be));
        sbuf.append(" lost=");
        sbuf.append(Long.toString(this.lostmpdu_be));
        sbuf.append(" retries=");
        sbuf.append(Long.toString(this.retries_be));
        sbuf.append(10);
        sbuf.append(" BK : ");
        sbuf.append(" rx=");
        sbuf.append(Long.toString(this.rxmpdu_bk));
        sbuf.append(" tx=");
        sbuf.append(Long.toString(this.txmpdu_bk));
        sbuf.append(" lost=");
        sbuf.append(Long.toString(this.lostmpdu_bk));
        sbuf.append(" retries=");
        sbuf.append(Long.toString(this.retries_bk));
        sbuf.append(10);
        sbuf.append(" VI : ");
        sbuf.append(" rx=");
        sbuf.append(Long.toString(this.rxmpdu_vi));
        sbuf.append(" tx=");
        sbuf.append(Long.toString(this.txmpdu_vi));
        sbuf.append(" lost=");
        sbuf.append(Long.toString(this.lostmpdu_vi));
        sbuf.append(" retries=");
        sbuf.append(Long.toString(this.retries_vi));
        sbuf.append(10);
        sbuf.append(" VO : ");
        sbuf.append(" rx=");
        sbuf.append(Long.toString(this.rxmpdu_vo));
        sbuf.append(" tx=");
        sbuf.append(Long.toString(this.txmpdu_vo));
        sbuf.append(" lost=");
        sbuf.append(Long.toString(this.lostmpdu_vo));
        sbuf.append(" retries=");
        sbuf.append(Long.toString(this.retries_vo));
        sbuf.append(10);
        sbuf.append(" on_time : ");
        sbuf.append(Integer.toString(this.on_time));
        sbuf.append(" rx_time=");
        sbuf.append(Integer.toString(this.rx_time));
        sbuf.append(" scan_time=");
        sbuf.append(Integer.toString(this.on_time_scan));
        sbuf.append(10);
        sbuf.append(" tx_time=");
        sbuf.append(Integer.toString(this.tx_time));
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(" tx_time_per_level=");
        stringBuilder.append(Arrays.toString(this.tx_time_per_level));
        sbuf.append(stringBuilder.toString());
        stringBuilder = new StringBuilder();
        stringBuilder.append(" ts=");
        stringBuilder.append(this.timeStampInMs);
        sbuf.append(stringBuilder.toString());
        return sbuf.toString();
    }
}
