package com.android.org.conscrypt;

import java.security.Provider;

public final class OpenSSLProvider extends Provider {
    private static final String PREFIX;
    private static final String STANDARD_EC_PRIVATE_KEY_INTERFACE_CLASS_NAME = "java.security.interfaces.ECPrivateKey";
    private static final String STANDARD_RSA_PRIVATE_KEY_INTERFACE_CLASS_NAME = "java.security.interfaces.RSAPrivateKey";
    private static final String STANDARD_RSA_PUBLIC_KEY_INTERFACE_CLASS_NAME = "java.security.interfaces.RSAPublicKey";
    private static final long serialVersionUID = 2996752495318905136L;

    static {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(OpenSSLProvider.class.getPackage().getName());
        stringBuilder.append(".");
        PREFIX = stringBuilder.toString();
    }

    public OpenSSLProvider() {
        this(Platform.getDefaultProviderName());
    }

    public OpenSSLProvider(String providerName) {
        super(providerName, 1.0d, "Android's OpenSSL-backed security provider");
        NativeCrypto.checkAvailability();
        Platform.setup();
        String classOpenSSLContextImpl = new StringBuilder();
        classOpenSSLContextImpl.append(PREFIX);
        classOpenSSLContextImpl.append("OpenSSLContextImpl");
        classOpenSSLContextImpl = classOpenSSLContextImpl.toString();
        String tls12SSLContext = new StringBuilder();
        tls12SSLContext.append(classOpenSSLContextImpl);
        tls12SSLContext.append("$TLSv12");
        tls12SSLContext = tls12SSLContext.toString();
        put("SSLContext.SSL", tls12SSLContext);
        put("SSLContext.TLS", tls12SSLContext);
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(classOpenSSLContextImpl);
        stringBuilder.append("$TLSv1");
        put("SSLContext.TLSv1", stringBuilder.toString());
        stringBuilder = new StringBuilder();
        stringBuilder.append(classOpenSSLContextImpl);
        stringBuilder.append("$TLSv11");
        put("SSLContext.TLSv1.1", stringBuilder.toString());
        put("SSLContext.TLSv1.2", tls12SSLContext);
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("DefaultSSLContextImpl");
        put("SSLContext.Default", stringBuilder.toString());
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("IvParameters$AES");
        put("AlgorithmParameters.AES", stringBuilder.toString());
        put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.2", "AES");
        put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.22", "AES");
        put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.42", "AES");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("IvParameters$ChaCha20");
        put("AlgorithmParameters.ChaCha20", stringBuilder.toString());
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("IvParameters$DESEDE");
        put("AlgorithmParameters.DESEDE", stringBuilder.toString());
        put("Alg.Alias.AlgorithmParameters.TDEA", "DESEDE");
        put("Alg.Alias.AlgorithmParameters.1.2.840.113549.3.7", "DESEDE");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("GCMParameters");
        put("AlgorithmParameters.GCM", stringBuilder.toString());
        put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.6", "GCM");
        put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.26", "GCM");
        put("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.1.46", "GCM");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OAEPParameters");
        put("AlgorithmParameters.OAEP", stringBuilder.toString());
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("ECParameters");
        put("AlgorithmParameters.EC", stringBuilder.toString());
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLMessageDigestJDK$SHA1");
        put("MessageDigest.SHA-1", stringBuilder.toString());
        put("Alg.Alias.MessageDigest.SHA1", "SHA-1");
        put("Alg.Alias.MessageDigest.SHA", "SHA-1");
        put("Alg.Alias.MessageDigest.1.3.14.3.2.26", "SHA-1");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLMessageDigestJDK$SHA224");
        put("MessageDigest.SHA-224", stringBuilder.toString());
        put("Alg.Alias.MessageDigest.SHA224", "SHA-224");
        put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.4", "SHA-224");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLMessageDigestJDK$SHA256");
        put("MessageDigest.SHA-256", stringBuilder.toString());
        put("Alg.Alias.MessageDigest.SHA256", "SHA-256");
        put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.1", "SHA-256");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLMessageDigestJDK$SHA384");
        put("MessageDigest.SHA-384", stringBuilder.toString());
        put("Alg.Alias.MessageDigest.SHA384", "SHA-384");
        put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.2", "SHA-384");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLMessageDigestJDK$SHA512");
        put("MessageDigest.SHA-512", stringBuilder.toString());
        put("Alg.Alias.MessageDigest.SHA512", "SHA-512");
        put("Alg.Alias.MessageDigest.2.16.840.1.101.3.4.2.3", "SHA-512");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLMessageDigestJDK$MD5");
        put("MessageDigest.MD5", stringBuilder.toString());
        put("Alg.Alias.MessageDigest.1.2.840.113549.2.5", "MD5");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$ARC4");
        put("KeyGenerator.ARC4", stringBuilder.toString());
        put("Alg.Alias.KeyGenerator.RC4", "ARC4");
        put("Alg.Alias.KeyGenerator.1.2.840.113549.3.4", "ARC4");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$AES");
        put("KeyGenerator.AES", stringBuilder.toString());
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$ChaCha20");
        put("KeyGenerator.ChaCha20", stringBuilder.toString());
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$DESEDE");
        put("KeyGenerator.DESEDE", stringBuilder.toString());
        put("Alg.Alias.KeyGenerator.TDEA", "DESEDE");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$HmacMD5");
        put("KeyGenerator.HmacMD5", stringBuilder.toString());
        put("Alg.Alias.KeyGenerator.1.3.6.1.5.5.8.1.1", "HmacMD5");
        put("Alg.Alias.KeyGenerator.HMAC-MD5", "HmacMD5");
        put("Alg.Alias.KeyGenerator.HMAC/MD5", "HmacMD5");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$HmacSHA1");
        put("KeyGenerator.HmacSHA1", stringBuilder.toString());
        put("Alg.Alias.KeyGenerator.1.2.840.113549.2.7", "HmacSHA1");
        put("Alg.Alias.KeyGenerator.1.3.6.1.5.5.8.1.2", "HmacSHA1");
        put("Alg.Alias.KeyGenerator.HMAC-SHA1", "HmacSHA1");
        put("Alg.Alias.KeyGenerator.HMAC/SHA1", "HmacSHA1");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$HmacSHA224");
        put("KeyGenerator.HmacSHA224", stringBuilder.toString());
        put("Alg.Alias.KeyGenerator.1.2.840.113549.2.8", "HmacSHA224");
        put("Alg.Alias.KeyGenerator.HMAC-SHA224", "HmacSHA224");
        put("Alg.Alias.KeyGenerator.HMAC/SHA224", "HmacSHA224");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$HmacSHA256");
        put("KeyGenerator.HmacSHA256", stringBuilder.toString());
        put("Alg.Alias.KeyGenerator.1.2.840.113549.2.9", "HmacSHA256");
        put("Alg.Alias.KeyGenerator.2.16.840.1.101.3.4.2.1", "HmacSHA256");
        put("Alg.Alias.KeyGenerator.HMAC-SHA256", "HmacSHA256");
        put("Alg.Alias.KeyGenerator.HMAC/SHA256", "HmacSHA256");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$HmacSHA384");
        put("KeyGenerator.HmacSHA384", stringBuilder.toString());
        put("Alg.Alias.KeyGenerator.1.2.840.113549.2.10", "HmacSHA384");
        put("Alg.Alias.KeyGenerator.HMAC-SHA384", "HmacSHA384");
        put("Alg.Alias.KeyGenerator.HMAC/SHA384", "HmacSHA384");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("KeyGeneratorImpl$HmacSHA512");
        put("KeyGenerator.HmacSHA512", stringBuilder.toString());
        put("Alg.Alias.KeyGenerator.1.2.840.113549.2.11", "HmacSHA512");
        put("Alg.Alias.KeyGenerator.HMAC-SHA512", "HmacSHA512");
        put("Alg.Alias.KeyGenerator.HMAC/SHA512", "HmacSHA512");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLRSAKeyPairGenerator");
        put("KeyPairGenerator.RSA", stringBuilder.toString());
        put("Alg.Alias.KeyPairGenerator.1.2.840.113549.1.1.1", "RSA");
        put("Alg.Alias.KeyPairGenerator.1.2.840.113549.1.1.7", "RSA");
        put("Alg.Alias.KeyPairGenerator.2.5.8.1.1", "RSA");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLECKeyPairGenerator");
        put("KeyPairGenerator.EC", stringBuilder.toString());
        put("Alg.Alias.KeyPairGenerator.1.2.840.10045.2.1", "EC");
        put("Alg.Alias.KeyPairGenerator.1.3.133.16.840.63.0.2", "EC");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLRSAKeyFactory");
        put("KeyFactory.RSA", stringBuilder.toString());
        put("Alg.Alias.KeyFactory.1.2.840.113549.1.1.1", "RSA");
        put("Alg.Alias.KeyFactory.1.2.840.113549.1.1.7", "RSA");
        put("Alg.Alias.KeyFactory.2.5.8.1.1", "RSA");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLECKeyFactory");
        put("KeyFactory.EC", stringBuilder.toString());
        put("Alg.Alias.KeyFactory.1.2.840.10045.2.1", "EC");
        put("Alg.Alias.KeyFactory.1.3.133.16.840.63.0.2", "EC");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("DESEDESecretKeyFactory");
        put("SecretKeyFactory.DESEDE", stringBuilder.toString());
        put("Alg.Alias.SecretKeyFactory.TDEA", "DESEDE");
        putECDHKeyAgreementImplClass("OpenSSLECDHKeyAgreement");
        putSignatureImplClass("MD5WithRSA", "OpenSSLSignature$MD5RSA");
        put("Alg.Alias.Signature.MD5WithRSAEncryption", "MD5WithRSA");
        put("Alg.Alias.Signature.MD5/RSA", "MD5WithRSA");
        put("Alg.Alias.Signature.1.2.840.113549.1.1.4", "MD5WithRSA");
        put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.4", "MD5WithRSA");
        put("Alg.Alias.Signature.1.2.840.113549.2.5with1.2.840.113549.1.1.1", "MD5WithRSA");
        putSignatureImplClass("SHA1WithRSA", "OpenSSLSignature$SHA1RSA");
        put("Alg.Alias.Signature.SHA1WithRSAEncryption", "SHA1WithRSA");
        put("Alg.Alias.Signature.SHA1/RSA", "SHA1WithRSA");
        put("Alg.Alias.Signature.SHA-1/RSA", "SHA1WithRSA");
        put("Alg.Alias.Signature.1.2.840.113549.1.1.5", "SHA1WithRSA");
        put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.5", "SHA1WithRSA");
        put("Alg.Alias.Signature.1.3.14.3.2.26with1.2.840.113549.1.1.1", "SHA1WithRSA");
        put("Alg.Alias.Signature.1.3.14.3.2.26with1.2.840.113549.1.1.5", "SHA1WithRSA");
        put("Alg.Alias.Signature.1.3.14.3.2.29", "SHA1WithRSA");
        put("Alg.Alias.Signature.OID.1.3.14.3.2.29", "SHA1WithRSA");
        putSignatureImplClass("SHA224WithRSA", "OpenSSLSignature$SHA224RSA");
        put("Alg.Alias.Signature.SHA224WithRSAEncryption", "SHA224WithRSA");
        put("Alg.Alias.Signature.SHA224/RSA", "SHA224WithRSA");
        put("Alg.Alias.Signature.1.2.840.113549.1.1.14", "SHA224WithRSA");
        put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.14", "SHA224WithRSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.4with1.2.840.113549.1.1.1", "SHA224WithRSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.4with1.2.840.113549.1.1.14", "SHA224WithRSA");
        putSignatureImplClass("SHA256WithRSA", "OpenSSLSignature$SHA256RSA");
        put("Alg.Alias.Signature.SHA256WithRSAEncryption", "SHA256WithRSA");
        put("Alg.Alias.Signature.SHA256/RSA", "SHA256WithRSA");
        put("Alg.Alias.Signature.1.2.840.113549.1.1.11", "SHA256WithRSA");
        put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.11", "SHA256WithRSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.1with1.2.840.113549.1.1.1", "SHA256WithRSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.1with1.2.840.113549.1.1.11", "SHA256WithRSA");
        putSignatureImplClass("SHA384WithRSA", "OpenSSLSignature$SHA384RSA");
        put("Alg.Alias.Signature.SHA384WithRSAEncryption", "SHA384WithRSA");
        put("Alg.Alias.Signature.SHA384/RSA", "SHA384WithRSA");
        put("Alg.Alias.Signature.1.2.840.113549.1.1.12", "SHA384WithRSA");
        put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.12", "SHA384WithRSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.2with1.2.840.113549.1.1.1", "SHA384WithRSA");
        putSignatureImplClass("SHA512WithRSA", "OpenSSLSignature$SHA512RSA");
        put("Alg.Alias.Signature.SHA512WithRSAEncryption", "SHA512WithRSA");
        put("Alg.Alias.Signature.SHA512/RSA", "SHA512WithRSA");
        put("Alg.Alias.Signature.1.2.840.113549.1.1.13", "SHA512WithRSA");
        put("Alg.Alias.Signature.OID.1.2.840.113549.1.1.13", "SHA512WithRSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.3with1.2.840.113549.1.1.1", "SHA512WithRSA");
        putRAWRSASignatureImplClass("OpenSSLSignatureRawRSA");
        putSignatureImplClass("NONEwithECDSA", "OpenSSLSignatureRawECDSA");
        putSignatureImplClass("SHA1withECDSA", "OpenSSLSignature$SHA1ECDSA");
        put("Alg.Alias.Signature.ECDSA", "SHA1withECDSA");
        put("Alg.Alias.Signature.ECDSAwithSHA1", "SHA1withECDSA");
        put("Alg.Alias.Signature.1.2.840.10045.4.1", "SHA1withECDSA");
        put("Alg.Alias.Signature.1.3.14.3.2.26with1.2.840.10045.2.1", "SHA1withECDSA");
        putSignatureImplClass("SHA224withECDSA", "OpenSSLSignature$SHA224ECDSA");
        put("Alg.Alias.Signature.SHA224/ECDSA", "SHA224withECDSA");
        put("Alg.Alias.Signature.1.2.840.10045.4.3.1", "SHA224withECDSA");
        put("Alg.Alias.Signature.OID.1.2.840.10045.4.3.1", "SHA224withECDSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.4with1.2.840.10045.2.1", "SHA224withECDSA");
        putSignatureImplClass("SHA256withECDSA", "OpenSSLSignature$SHA256ECDSA");
        put("Alg.Alias.Signature.SHA256/ECDSA", "SHA256withECDSA");
        put("Alg.Alias.Signature.1.2.840.10045.4.3.2", "SHA256withECDSA");
        put("Alg.Alias.Signature.OID.1.2.840.10045.4.3.2", "SHA256withECDSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.1with1.2.840.10045.2.1", "SHA256withECDSA");
        putSignatureImplClass("SHA384withECDSA", "OpenSSLSignature$SHA384ECDSA");
        put("Alg.Alias.Signature.SHA384/ECDSA", "SHA384withECDSA");
        put("Alg.Alias.Signature.1.2.840.10045.4.3.3", "SHA384withECDSA");
        put("Alg.Alias.Signature.OID.1.2.840.10045.4.3.3", "SHA384withECDSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.2with1.2.840.10045.2.1", "SHA384withECDSA");
        putSignatureImplClass("SHA512withECDSA", "OpenSSLSignature$SHA512ECDSA");
        put("Alg.Alias.Signature.SHA512/ECDSA", "SHA512withECDSA");
        put("Alg.Alias.Signature.1.2.840.10045.4.3.4", "SHA512withECDSA");
        put("Alg.Alias.Signature.OID.1.2.840.10045.4.3.4", "SHA512withECDSA");
        put("Alg.Alias.Signature.2.16.840.1.101.3.4.2.3with1.2.840.10045.2.1", "SHA512withECDSA");
        putSignatureImplClass("SHA1withRSA/PSS", "OpenSSLSignature$SHA1RSAPSS");
        put("Alg.Alias.Signature.SHA1withRSAandMGF1", "SHA1withRSA/PSS");
        putSignatureImplClass("SHA224withRSA/PSS", "OpenSSLSignature$SHA224RSAPSS");
        put("Alg.Alias.Signature.SHA224withRSAandMGF1", "SHA224withRSA/PSS");
        putSignatureImplClass("SHA256withRSA/PSS", "OpenSSLSignature$SHA256RSAPSS");
        put("Alg.Alias.Signature.SHA256withRSAandMGF1", "SHA256withRSA/PSS");
        putSignatureImplClass("SHA384withRSA/PSS", "OpenSSLSignature$SHA384RSAPSS");
        put("Alg.Alias.Signature.SHA384withRSAandMGF1", "SHA384withRSA/PSS");
        putSignatureImplClass("SHA512withRSA/PSS", "OpenSSLSignature$SHA512RSAPSS");
        put("Alg.Alias.Signature.SHA512withRSAandMGF1", "SHA512withRSA/PSS");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLRandom");
        put("SecureRandom.SHA1PRNG", stringBuilder.toString());
        put("SecureRandom.SHA1PRNG ImplementedIn", "Software");
        putRSACipherImplClass("RSA/ECB/NoPadding", "OpenSSLCipherRSA$Raw");
        put("Alg.Alias.Cipher.RSA/None/NoPadding", "RSA/ECB/NoPadding");
        putRSACipherImplClass("RSA/ECB/PKCS1Padding", "OpenSSLCipherRSA$PKCS1");
        put("Alg.Alias.Cipher.RSA/None/PKCS1Padding", "RSA/ECB/PKCS1Padding");
        putRSACipherImplClass("RSA/ECB/OAEPPadding", "OpenSSLCipherRSA$OAEP$SHA1");
        put("Alg.Alias.Cipher.RSA/None/OAEPPadding", "RSA/ECB/OAEPPadding");
        putRSACipherImplClass("RSA/ECB/OAEPWithSHA-1AndMGF1Padding", "OpenSSLCipherRSA$OAEP$SHA1");
        put("Alg.Alias.Cipher.RSA/None/OAEPWithSHA-1AndMGF1Padding", "RSA/ECB/OAEPWithSHA-1AndMGF1Padding");
        putRSACipherImplClass("RSA/ECB/OAEPWithSHA-224AndMGF1Padding", "OpenSSLCipherRSA$OAEP$SHA224");
        put("Alg.Alias.Cipher.RSA/None/OAEPWithSHA-224AndMGF1Padding", "RSA/ECB/OAEPWithSHA-224AndMGF1Padding");
        putRSACipherImplClass("RSA/ECB/OAEPWithSHA-256AndMGF1Padding", "OpenSSLCipherRSA$OAEP$SHA256");
        put("Alg.Alias.Cipher.RSA/None/OAEPWithSHA-256AndMGF1Padding", "RSA/ECB/OAEPWithSHA-256AndMGF1Padding");
        putRSACipherImplClass("RSA/ECB/OAEPWithSHA-384AndMGF1Padding", "OpenSSLCipherRSA$OAEP$SHA384");
        put("Alg.Alias.Cipher.RSA/None/OAEPWithSHA-384AndMGF1Padding", "RSA/ECB/OAEPWithSHA-384AndMGF1Padding");
        putRSACipherImplClass("RSA/ECB/OAEPWithSHA-512AndMGF1Padding", "OpenSSLCipherRSA$OAEP$SHA512");
        put("Alg.Alias.Cipher.RSA/None/OAEPWithSHA-512AndMGF1Padding", "RSA/ECB/OAEPWithSHA-512AndMGF1Padding");
        putSymmetricCipherImplClass("AES/ECB/NoPadding", "OpenSSLCipher$EVP_CIPHER$AES$ECB$NoPadding");
        putSymmetricCipherImplClass("AES/ECB/PKCS5Padding", "OpenSSLCipher$EVP_CIPHER$AES$ECB$PKCS5Padding");
        put("Alg.Alias.Cipher.AES/ECB/PKCS7Padding", "AES/ECB/PKCS5Padding");
        putSymmetricCipherImplClass("AES/CBC/NoPadding", "OpenSSLCipher$EVP_CIPHER$AES$CBC$NoPadding");
        putSymmetricCipherImplClass("AES/CBC/PKCS5Padding", "OpenSSLCipher$EVP_CIPHER$AES$CBC$PKCS5Padding");
        put("Alg.Alias.Cipher.AES/CBC/PKCS7Padding", "AES/CBC/PKCS5Padding");
        putSymmetricCipherImplClass("AES/CTR/NoPadding", "OpenSSLCipher$EVP_CIPHER$AES$CTR");
        putSymmetricCipherImplClass("AES_128/ECB/NoPadding", "OpenSSLCipher$EVP_CIPHER$AES_128$ECB$NoPadding");
        putSymmetricCipherImplClass("AES_128/ECB/PKCS5Padding", "OpenSSLCipher$EVP_CIPHER$AES_128$ECB$PKCS5Padding");
        put("Alg.Alias.Cipher.AES_128/ECB/PKCS7Padding", "AES_128/ECB/PKCS5Padding");
        putSymmetricCipherImplClass("AES_128/CBC/NoPadding", "OpenSSLCipher$EVP_CIPHER$AES_128$CBC$NoPadding");
        putSymmetricCipherImplClass("AES_128/CBC/PKCS5Padding", "OpenSSLCipher$EVP_CIPHER$AES_128$CBC$PKCS5Padding");
        put("Alg.Alias.Cipher.AES_128/CBC/PKCS7Padding", "AES_128/CBC/PKCS5Padding");
        put("Alg.Alias.Cipher.PBEWithHmacSHA1AndAES_128", "AES_128/CBC/PKCS5PADDING");
        put("Alg.Alias.Cipher.PBEWithHmacSHA224AndAES_128", "AES_128/CBC/PKCS5PADDING");
        put("Alg.Alias.Cipher.PBEWithHmacSHA256AndAES_128", "AES_128/CBC/PKCS5PADDING");
        put("Alg.Alias.Cipher.PBEWithHmacSHA384AndAES_128", "AES_128/CBC/PKCS5PADDING");
        put("Alg.Alias.Cipher.PBEWithHmacSHA512AndAES_128", "AES_128/CBC/PKCS5PADDING");
        putSymmetricCipherImplClass("AES_256/ECB/NoPadding", "OpenSSLCipher$EVP_CIPHER$AES_256$ECB$NoPadding");
        putSymmetricCipherImplClass("AES_256/ECB/PKCS5Padding", "OpenSSLCipher$EVP_CIPHER$AES_256$ECB$PKCS5Padding");
        put("Alg.Alias.Cipher.AES_256/ECB/PKCS7Padding", "AES_256/ECB/PKCS5Padding");
        putSymmetricCipherImplClass("AES_256/CBC/NoPadding", "OpenSSLCipher$EVP_CIPHER$AES_256$CBC$NoPadding");
        putSymmetricCipherImplClass("AES_256/CBC/PKCS5Padding", "OpenSSLCipher$EVP_CIPHER$AES_256$CBC$PKCS5Padding");
        put("Alg.Alias.Cipher.AES_256/CBC/PKCS7Padding", "AES_256/CBC/PKCS5Padding");
        put("Alg.Alias.Cipher.PBEWithHmacSHA1AndAES_256", "AES_256/CBC/PKCS5PADDING");
        put("Alg.Alias.Cipher.PBEWithHmacSHA224AndAES_256", "AES_256/CBC/PKCS5PADDING");
        put("Alg.Alias.Cipher.PBEWithHmacSHA256AndAES_256", "AES_256/CBC/PKCS5PADDING");
        put("Alg.Alias.Cipher.PBEWithHmacSHA384AndAES_256", "AES_256/CBC/PKCS5PADDING");
        put("Alg.Alias.Cipher.PBEWithHmacSHA512AndAES_256", "AES_256/CBC/PKCS5PADDING");
        putSymmetricCipherImplClass("DESEDE/CBC/NoPadding", "OpenSSLCipher$EVP_CIPHER$DESEDE$CBC$NoPadding");
        putSymmetricCipherImplClass("DESEDE/CBC/PKCS5Padding", "OpenSSLCipher$EVP_CIPHER$DESEDE$CBC$PKCS5Padding");
        put("Alg.Alias.Cipher.DESEDE/CBC/PKCS7Padding", "DESEDE/CBC/PKCS5Padding");
        putSymmetricCipherImplClass("ARC4", "OpenSSLCipher$EVP_CIPHER$ARC4");
        put("Alg.Alias.Cipher.ARCFOUR", "ARC4");
        put("Alg.Alias.Cipher.RC4", "ARC4");
        put("Alg.Alias.Cipher.1.2.840.113549.3.4", "ARC4");
        put("Alg.Alias.Cipher.OID.1.2.840.113549.3.4", "ARC4");
        putSymmetricCipherImplClass("AES/GCM/NoPadding", "OpenSSLCipher$EVP_AEAD$AES$GCM");
        put("Alg.Alias.Cipher.GCM", "AES/GCM/NoPadding");
        put("Alg.Alias.Cipher.2.16.840.1.101.3.4.1.6", "AES/GCM/NoPadding");
        put("Alg.Alias.Cipher.2.16.840.1.101.3.4.1.26", "AES/GCM/NoPadding");
        put("Alg.Alias.Cipher.2.16.840.1.101.3.4.1.46", "AES/GCM/NoPadding");
        putSymmetricCipherImplClass("AES_128/GCM/NoPadding", "OpenSSLCipher$EVP_AEAD$AES$GCM$AES_128");
        putSymmetricCipherImplClass("AES_256/GCM/NoPadding", "OpenSSLCipher$EVP_AEAD$AES$GCM$AES_256");
        putSymmetricCipherImplClass("ChaCha20", "OpenSSLCipherChaCha20");
        putSymmetricCipherImplClass("ChaCha20/Poly1305/NoPadding", "OpenSSLCipher$EVP_AEAD$ChaCha20");
        putMacImplClass("HmacMD5", "OpenSSLMac$HmacMD5");
        put("Alg.Alias.Mac.1.3.6.1.5.5.8.1.1", "HmacMD5");
        put("Alg.Alias.Mac.HMAC-MD5", "HmacMD5");
        put("Alg.Alias.Mac.HMAC/MD5", "HmacMD5");
        putMacImplClass("HmacSHA1", "OpenSSLMac$HmacSHA1");
        put("Alg.Alias.Mac.1.2.840.113549.2.7", "HmacSHA1");
        put("Alg.Alias.Mac.1.3.6.1.5.5.8.1.2", "HmacSHA1");
        put("Alg.Alias.Mac.HMAC-SHA1", "HmacSHA1");
        put("Alg.Alias.Mac.HMAC/SHA1", "HmacSHA1");
        putMacImplClass("HmacSHA224", "OpenSSLMac$HmacSHA224");
        put("Alg.Alias.Mac.1.2.840.113549.2.8", "HmacSHA224");
        put("Alg.Alias.Mac.HMAC-SHA224", "HmacSHA224");
        put("Alg.Alias.Mac.HMAC/SHA224", "HmacSHA224");
        put("Alg.Alias.Mac.PBEWITHHMACSHA224", "HmacSHA224");
        putMacImplClass("HmacSHA256", "OpenSSLMac$HmacSHA256");
        put("Alg.Alias.Mac.1.2.840.113549.2.9", "HmacSHA256");
        put("Alg.Alias.Mac.2.16.840.1.101.3.4.2.1", "HmacSHA256");
        put("Alg.Alias.Mac.HMAC-SHA256", "HmacSHA256");
        put("Alg.Alias.Mac.HMAC/SHA256", "HmacSHA256");
        put("Alg.Alias.Mac.PBEWITHHMACSHA256", "HmacSHA256");
        putMacImplClass("HmacSHA384", "OpenSSLMac$HmacSHA384");
        put("Alg.Alias.Mac.1.2.840.113549.2.10", "HmacSHA384");
        put("Alg.Alias.Mac.HMAC-SHA384", "HmacSHA384");
        put("Alg.Alias.Mac.HMAC/SHA384", "HmacSHA384");
        put("Alg.Alias.Mac.PBEWITHHMACSHA384", "HmacSHA384");
        putMacImplClass("HmacSHA512", "OpenSSLMac$HmacSHA512");
        put("Alg.Alias.Mac.1.2.840.113549.2.11", "HmacSHA512");
        put("Alg.Alias.Mac.HMAC-SHA512", "HmacSHA512");
        put("Alg.Alias.Mac.HMAC/SHA512", "HmacSHA512");
        put("Alg.Alias.Mac.PBEWITHHMACSHA512", "HmacSHA512");
        stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append("OpenSSLX509CertificateFactory");
        put("CertificateFactory.X509", stringBuilder.toString());
        put("Alg.Alias.CertificateFactory.X.509", "X509");
    }

    private void putMacImplClass(String algorithm, String className) {
        String supportedKeyClasses = new StringBuilder();
        supportedKeyClasses.append(PREFIX);
        supportedKeyClasses.append("OpenSSLKeyHolder");
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("Mac.");
        stringBuilder.append(algorithm);
        String stringBuilder2 = stringBuilder.toString();
        StringBuilder stringBuilder3 = new StringBuilder();
        stringBuilder3.append(PREFIX);
        stringBuilder3.append(className);
        putImplClassWithKeyConstraints(stringBuilder2, stringBuilder3.toString(), supportedKeyClasses.toString(), "RAW");
    }

    private void putSymmetricCipherImplClass(String transformation, String className) {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("Cipher.");
        stringBuilder.append(transformation);
        String stringBuilder2 = stringBuilder.toString();
        StringBuilder stringBuilder3 = new StringBuilder();
        stringBuilder3.append(PREFIX);
        stringBuilder3.append(className);
        putImplClassWithKeyConstraints(stringBuilder2, stringBuilder3.toString(), null, "RAW");
    }

    private void putRSACipherImplClass(String transformation, String className) {
        String supportedKeyClasses = new StringBuilder();
        supportedKeyClasses.append(PREFIX);
        supportedKeyClasses.append("OpenSSLRSAPrivateKey|");
        supportedKeyClasses.append(STANDARD_RSA_PRIVATE_KEY_INTERFACE_CLASS_NAME);
        supportedKeyClasses.append("|");
        supportedKeyClasses.append(PREFIX);
        supportedKeyClasses.append("OpenSSLRSAPublicKey|");
        supportedKeyClasses.append(STANDARD_RSA_PUBLIC_KEY_INTERFACE_CLASS_NAME);
        supportedKeyClasses = supportedKeyClasses.toString();
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("Cipher.");
        stringBuilder.append(transformation);
        String stringBuilder2 = stringBuilder.toString();
        StringBuilder stringBuilder3 = new StringBuilder();
        stringBuilder3.append(PREFIX);
        stringBuilder3.append(className);
        putImplClassWithKeyConstraints(stringBuilder2, stringBuilder3.toString(), supportedKeyClasses, null);
    }

    private void putSignatureImplClass(String algorithm, String className) {
        String supportedKeyClasses = new StringBuilder();
        supportedKeyClasses.append(PREFIX);
        supportedKeyClasses.append("OpenSSLKeyHolder|");
        supportedKeyClasses.append(STANDARD_RSA_PRIVATE_KEY_INTERFACE_CLASS_NAME);
        supportedKeyClasses.append("|");
        supportedKeyClasses.append(STANDARD_EC_PRIVATE_KEY_INTERFACE_CLASS_NAME);
        supportedKeyClasses.append("|");
        supportedKeyClasses.append(STANDARD_RSA_PUBLIC_KEY_INTERFACE_CLASS_NAME);
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("Signature.");
        stringBuilder.append(algorithm);
        String stringBuilder2 = stringBuilder.toString();
        StringBuilder stringBuilder3 = new StringBuilder();
        stringBuilder3.append(PREFIX);
        stringBuilder3.append(className);
        putImplClassWithKeyConstraints(stringBuilder2, stringBuilder3.toString(), supportedKeyClasses.toString(), "PKCS#8|X.509");
    }

    private void putRAWRSASignatureImplClass(String className) {
        String supportedKeyClasses = new StringBuilder();
        supportedKeyClasses.append(PREFIX);
        supportedKeyClasses.append("OpenSSLRSAPrivateKey|");
        supportedKeyClasses.append(STANDARD_RSA_PRIVATE_KEY_INTERFACE_CLASS_NAME);
        supportedKeyClasses.append("|");
        supportedKeyClasses.append(PREFIX);
        supportedKeyClasses.append("OpenSSLRSAPublicKey|");
        supportedKeyClasses.append(STANDARD_RSA_PUBLIC_KEY_INTERFACE_CLASS_NAME);
        supportedKeyClasses = supportedKeyClasses.toString();
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append(className);
        putImplClassWithKeyConstraints("Signature.NONEwithRSA", stringBuilder.toString(), supportedKeyClasses, null);
    }

    private void putECDHKeyAgreementImplClass(String className) {
        String supportedKeyClasses = new StringBuilder();
        supportedKeyClasses.append(PREFIX);
        supportedKeyClasses.append("OpenSSLKeyHolder|");
        supportedKeyClasses.append(STANDARD_EC_PRIVATE_KEY_INTERFACE_CLASS_NAME);
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(PREFIX);
        stringBuilder.append(className);
        putImplClassWithKeyConstraints("KeyAgreement.ECDH", stringBuilder.toString(), supportedKeyClasses.toString(), "PKCS#8");
    }

    private void putImplClassWithKeyConstraints(String typeAndAlgName, String fullyQualifiedClassName, String supportedKeyClasses, String supportedKeyFormats) {
        StringBuilder stringBuilder;
        put(typeAndAlgName, fullyQualifiedClassName);
        if (supportedKeyClasses != null) {
            stringBuilder = new StringBuilder();
            stringBuilder.append(typeAndAlgName);
            stringBuilder.append(" SupportedKeyClasses");
            put(stringBuilder.toString(), supportedKeyClasses);
        }
        if (supportedKeyFormats != null) {
            stringBuilder = new StringBuilder();
            stringBuilder.append(typeAndAlgName);
            stringBuilder.append(" SupportedKeyFormats");
            put(stringBuilder.toString(), supportedKeyFormats);
        }
    }
}
