package com.huawei.g11n.tmr.address;

import java.util.regex.Pattern;

public class ReguEx {
    String bigLett;
    String blank;
    String blank2;
    String boundL;
    String boundR;
    String city;
    String cityPre;
    String citySuf;
    String code;
    String code_a = "(?<!\\d)(?:\\d{5}(?:\\s*-\\s*\\d{4})?)(?!\\d)";
    String code_b = "\\b(?:(?:[A-Z]{1,2}[0-9]{1,2} [0-9][A-Z]{2})|(?:[A-Z]{1,2}[0-9][A-Z] [0-9][A-Z]{2}))\\b";
    String dire;
    String letter;
    String location;
    String numBig;
    String numLett;
    String number;
    Pattern p1346;
    Pattern p28;
    Pattern p2s;
    Pattern p52;
    Pattern p52_sub;
    Pattern p52s;
    String post_box;
    String preAll;
    String preBuilding;
    String preCity;
    String preCityIn;
    String preRoad;
    String preState;
    String pre_s2;
    String pre_s52;
    String punc;
    String road;
    String roadSuf;
    String roadSuf_sub;
    String road_sub;
    String road_suite;
    String s52;
    String s52_sub;
    String state;
    String sufS;
    String word_1;
    String word_2;
    String word_23;
    String word_3;
    String word_4;
    String word_5;

    ReguEx() {
        StringBuilder stringBuilder = new StringBuilder("(?:(?:");
        stringBuilder.append(this.code_a);
        stringBuilder.append(")");
        stringBuilder.append("|(?:");
        stringBuilder.append(this.code_b);
        stringBuilder.append("))");
        this.code = stringBuilder.toString();
        this.number = "[0-9]";
        this.numBig = "[0-9A-Z]";
        this.numLett = "[0-9A-Za-z]";
        this.bigLett = "[A-Z]";
        this.letter = "[A-Za-z]";
        this.preState = "(?:(?i)in|of)";
        this.preCityIn = "(?:(?i)in|at|on|of)";
        this.preCity = "(?:(?i)in|at|of|from)";
        this.preRoad = "(?:(?i)in|at|on)";
        this.preBuilding = "(?:(?i)in|at|to|from|near|reach)";
        this.preAll = "(?:(?i)in|on|at|of|from|to|for|near)";
        this.dire = "(?:(?i)[nesw]|north|west|east|south|northeast|northwest|southeast|southwest|ne|nw|se|sw)\\.?";
        this.roadSuf = "(?:(?:(?i)boulevard|avenue|street|freeway|road|circle|lane|drive|court|ally|parkway|Crescent|Highway|(?:Ave|AV|Blvd|Cir|Ct|Dr|Ln|Pkwy|Rd|Sq|St|Fwy)\\.?)|Way|WAY)";
        this.roadSuf_sub = "(?:(?i)street|boulevard|avenue|lane|ave|av|blvd|ln|rd|st|crescent)(?:\\.?)";
        this.cityPre = "(?:(?i)uptown|downtown)";
        this.citySuf = "(?:(?i)town|city|county|uptown|downtown)";
        this.boundL = "(?<![a-zA-Z])";
        this.boundR = "(?![a-zA-Z])";
        this.blank = "(?:\\s*,\\s*|\\s+)";
        this.blank2 = "(\\s*[,:]\\s*|\\s*)";
        this.sufS = "(?:'s|'S|')";
        this.punc = "(?:(?:[-&,.])|\\(|\\)|\"|/|\\s)";
        stringBuilder = new StringBuilder(String.valueOf(this.bigLett));
        stringBuilder.append(this.letter);
        stringBuilder.append("*");
        stringBuilder.append(this.sufS);
        stringBuilder.append("?");
        this.word_1 = stringBuilder.toString();
        stringBuilder = new StringBuilder(String.valueOf(this.bigLett));
        stringBuilder.append(this.numLett);
        stringBuilder.append("*");
        stringBuilder.append(this.sufS);
        stringBuilder.append("?");
        this.word_2 = stringBuilder.toString();
        stringBuilder = new StringBuilder(String.valueOf(this.number));
        stringBuilder.append(this.numLett);
        stringBuilder.append("*");
        stringBuilder.append(this.letter);
        stringBuilder.append(this.sufS);
        stringBuilder.append("?");
        this.word_3 = stringBuilder.toString();
        stringBuilder = new StringBuilder("(?:");
        stringBuilder.append(this.word_2);
        stringBuilder.append("|");
        stringBuilder.append(this.word_3);
        stringBuilder.append(")");
        this.word_23 = stringBuilder.toString();
        stringBuilder = new StringBuilder(String.valueOf(this.numBig));
        stringBuilder.append(this.numLett);
        stringBuilder.append("*");
        stringBuilder.append(this.sufS);
        stringBuilder.append("?");
        this.word_4 = stringBuilder.toString();
        stringBuilder = new StringBuilder(String.valueOf(this.numLett));
        stringBuilder.append("+");
        stringBuilder.append(this.sufS);
        stringBuilder.append("?");
        this.word_5 = stringBuilder.toString();
        this.state = "(?:(?:(?i)(?:Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Lississippi|Missouri|Montana|Nebraska|Nevada|New Jersey|New Mexico|New York|North Carolian|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|RL|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming|AL|WY|AK|AZ|AR|CA|Co|CT|DE|FL|GA|ID|IL|IA|KS|KY|LA|MD|MA|MI|MN|MS|MO|MT|NE|NV|NJ|NM|NY|NC|ND|PA|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI))|(?:HI|OR|ME|OK|OH))\\.?(?:(?i)\\s+state)?";
        this.location = "(?:(?:(?i)(?:park|center|hotel|bar|hospital|theater|theatre|building|lounge|store|market|apartment|restaurant|museum|university|college|school|tower|guesthouse|mansion|motel|club|cafe|airport|stadium|station|bridge|bodega|tavern|boutique|zoo|mall|bkstore|inn|hostel|resort|institute|library|kingdergarten|cafeteria|bistro|canteen|hall|castle|garden|square|plaza|gallery|pier|wharf|shop|outlet|supermarket|district|clinic|cinema|gym|gymnasium|bowl|bus\\s+station|train\\s+station))|(?:House|HOUSE))";
        stringBuilder = new StringBuilder("(?:\\d+th\\s+)?");
        stringBuilder.append(this.boundL);
        stringBuilder.append("suite");
        stringBuilder.append("(?:(?:\\s*\\d+(?:\\s*-?\\s*");
        stringBuilder.append(this.letter);
        stringBuilder.append(")?)|(?:\\s+");
        stringBuilder.append(this.letter);
        stringBuilder.append(")|(?:(?i)\\s+level(?:\\s+");
        stringBuilder.append(this.letter);
        stringBuilder.append("?)))?(?!\\w)");
        this.road_suite = stringBuilder.toString();
        stringBuilder = new StringBuilder("(?:(?<![a-zA-Z0-9])(?:(?:(?:(?:#)?\\d+(?:-\\d+)?)");
        stringBuilder.append(this.blank);
        stringBuilder.append("(?:");
        stringBuilder.append(this.dire);
        stringBuilder.append("\\s+)?)?");
        stringBuilder.append("(?:");
        stringBuilder.append(this.word_23);
        stringBuilder.append("(?:\\s+(?:(?i)(?:and|&)\\s+)?))*?");
        stringBuilder.append(this.word_23);
        stringBuilder.append("\\s+");
        stringBuilder.append(this.roadSuf);
        stringBuilder.append(this.boundR);
        stringBuilder.append("(?:\\s+");
        stringBuilder.append(this.dire);
        stringBuilder.append(this.boundR);
        stringBuilder.append(")?");
        stringBuilder.append("(?:");
        stringBuilder.append(this.blank);
        stringBuilder.append(this.road_suite);
        stringBuilder.append(")?");
        stringBuilder.append("))");
        this.road = stringBuilder.toString();
        stringBuilder = new StringBuilder("(((?:");
        stringBuilder.append(this.cityPre);
        stringBuilder.append("\\s+)?(?:");
        stringBuilder.append(this.word_1);
        stringBuilder.append("\\s+(?:");
        stringBuilder.append(this.preCityIn);
        stringBuilder.append("\\s+)?){0,3}?");
        stringBuilder.append(this.word_1);
        stringBuilder.append("(?:\\s+");
        stringBuilder.append(this.citySuf);
        stringBuilder.append(")?");
        stringBuilder.append("(?:");
        stringBuilder.append(this.blank);
        stringBuilder.append("(?:");
        stringBuilder.append(this.preState);
        stringBuilder.append("\\s+)?");
        stringBuilder.append(this.state);
        stringBuilder.append("))");
        stringBuilder.append("|(?:(?:");
        stringBuilder.append(this.cityPre);
        stringBuilder.append("\\s+)?(?:");
        stringBuilder.append(this.word_1);
        stringBuilder.append("\\s+(?:");
        stringBuilder.append(this.preCityIn);
        stringBuilder.append("\\s+)?){0,3}");
        stringBuilder.append(this.word_1);
        stringBuilder.append("))");
        stringBuilder.append(this.boundR);
        this.city = stringBuilder.toString();
        stringBuilder = new StringBuilder(String.valueOf(this.boundL));
        stringBuilder.append("(?i)");
        stringBuilder.append("(?:(?:PO\\s*BOX\\s*\\d+(?:\\s+PMB\\s*\\d+)?)");
        stringBuilder.append("|(?:(?:Rural\\s+Route)|(?:RR))\\s*\\d+\\s+BOX\\s*\\d+\\s+PMB\\s*\\d+");
        stringBuilder.append("|\\d+\\s+PMB\\s*\\d+(?:(?:(?:Rural\\s+Route)|(?:RR))\\s*\\d+\\s+BOX\\s*\\d+)?)");
        this.post_box = stringBuilder.toString();
        stringBuilder = new StringBuilder("((?:");
        stringBuilder.append(this.road);
        stringBuilder.append(this.blank);
        stringBuilder.append("(?:(?i)(?:and|&)\\s+)?");
        stringBuilder.append(")*");
        stringBuilder.append(this.road);
        stringBuilder.append(")");
        stringBuilder.append("(");
        stringBuilder.append("(");
        stringBuilder.append(this.blank);
        stringBuilder.append("(?:");
        stringBuilder.append(this.preCity);
        stringBuilder.append("\\s+)?)");
        stringBuilder.append("(");
        stringBuilder.append(this.post_box);
        stringBuilder.append(this.blank);
        stringBuilder.append(")?");
        stringBuilder.append(this.city);
        stringBuilder.append("(");
        stringBuilder.append(this.blank);
        stringBuilder.append(this.code);
        stringBuilder.append(")?");
        stringBuilder.append(")?");
        this.s52 = stringBuilder.toString();
        stringBuilder = new StringBuilder("(\\W+(?:");
        stringBuilder.append(this.preRoad);
        stringBuilder.append("\\s+(?:the\\s+)?)?|\\W+)");
        this.pre_s52 = stringBuilder.toString();
        this.pre_s2 = "(\\W+(?:(?i)(?:in|at|of|from)\\s+(?:the\\s+)?)?|\\W+)";
        this.p52 = Pattern.compile(this.s52);
        stringBuilder = new StringBuilder(String.valueOf(this.pre_s52));
        stringBuilder.append(this.s52);
        this.p52s = Pattern.compile(stringBuilder.toString());
        stringBuilder = new StringBuilder(String.valueOf(this.pre_s2));
        stringBuilder.append("(");
        stringBuilder.append(this.post_box);
        stringBuilder.append(this.blank);
        stringBuilder.append(")?");
        stringBuilder.append(this.city);
        stringBuilder.append("(?:");
        stringBuilder.append(this.blank2);
        stringBuilder.append("(");
        stringBuilder.append(this.code);
        stringBuilder.append("))?");
        this.p2s = Pattern.compile(stringBuilder.toString());
        stringBuilder = new StringBuilder("(?:");
        stringBuilder.append(this.boundL);
        stringBuilder.append(this.preBuilding);
        stringBuilder.append("\\s+(?:(?i)the\\s+)?)?");
        stringBuilder.append(this.boundL);
        stringBuilder.append("(?:(?:(?:");
        stringBuilder.append(this.word_4);
        stringBuilder.append("|south|east|north|west)");
        stringBuilder.append(this.boundR);
        stringBuilder.append("\\s*)");
        stringBuilder.append("|");
        stringBuilder.append(this.location);
        stringBuilder.append(this.boundR);
        stringBuilder.append("\\s*)");
        stringBuilder.append("(?:");
        stringBuilder.append("((?:");
        stringBuilder.append(this.boundL);
        stringBuilder.append(this.word_4);
        stringBuilder.append(this.boundR);
        stringBuilder.append(")*)");
        stringBuilder.append("(?:(?:");
        stringBuilder.append(this.boundL);
        stringBuilder.append(this.location);
        stringBuilder.append(this.boundR);
        stringBuilder.append("|");
        stringBuilder.append(this.boundL);
        stringBuilder.append(this.preAll);
        stringBuilder.append(this.boundR);
        stringBuilder.append("|");
        stringBuilder.append(this.boundL);
        stringBuilder.append(this.citySuf);
        stringBuilder.append(this.boundR);
        stringBuilder.append("|");
        stringBuilder.append(this.punc);
        stringBuilder.append("|");
        stringBuilder.append(this.boundL);
        stringBuilder.append("(?:(?i)and)");
        stringBuilder.append(this.boundR);
        stringBuilder.append("|");
        stringBuilder.append(this.boundL);
        stringBuilder.append(this.state);
        stringBuilder.append(this.boundR);
        stringBuilder.append("|");
        stringBuilder.append(this.boundL);
        stringBuilder.append(this.roadSuf);
        stringBuilder.append(this.boundR);
        stringBuilder.append("|(?<![a-zA-Z'])");
        stringBuilder.append(this.dire);
        stringBuilder.append(this.boundR);
        stringBuilder.append("|");
        stringBuilder.append(this.boundL);
        stringBuilder.append("(?:(?i)the)");
        stringBuilder.append(this.boundR);
        stringBuilder.append(")*)");
        stringBuilder.append(")*");
        this.p1346 = Pattern.compile(stringBuilder.toString());
        stringBuilder = new StringBuilder("((");
        stringBuilder.append(this.post_box);
        stringBuilder.append(this.blank);
        stringBuilder.append(")?");
        stringBuilder.append(this.city);
        stringBuilder.append(")?");
        stringBuilder.append(this.blank2);
        stringBuilder.append("(");
        stringBuilder.append(this.code);
        stringBuilder.append(")");
        this.p28 = Pattern.compile(stringBuilder.toString());
        stringBuilder = new StringBuilder("(?:");
        stringBuilder.append(this.boundL);
        stringBuilder.append("(?:");
        stringBuilder.append(this.preRoad);
        stringBuilder.append("(?:\\s+");
        stringBuilder.append(this.number);
        stringBuilder.append("{3,5})?|(?:");
        stringBuilder.append(this.preRoad);
        stringBuilder.append("\\s+)?");
        stringBuilder.append(this.number);
        stringBuilder.append("{3,5})");
        stringBuilder.append("\\s+(?:");
        stringBuilder.append(this.word_5);
        stringBuilder.append("\\s+){1,3}");
        stringBuilder.append(this.roadSuf_sub);
        stringBuilder.append(this.boundR);
        stringBuilder.append("(?:\\s+");
        stringBuilder.append(this.dire);
        stringBuilder.append(this.boundR);
        stringBuilder.append(")?");
        stringBuilder.append("(?:");
        stringBuilder.append(this.blank);
        stringBuilder.append(this.road_suite);
        stringBuilder.append(")?)");
        this.road_sub = stringBuilder.toString();
        stringBuilder = new StringBuilder("(");
        stringBuilder.append(this.road_sub);
        stringBuilder.append(")");
        stringBuilder.append("(");
        stringBuilder.append("(");
        stringBuilder.append(this.blank);
        stringBuilder.append("(?:");
        stringBuilder.append(this.preCity);
        stringBuilder.append("\\s+)?)");
        stringBuilder.append("(");
        stringBuilder.append(this.post_box);
        stringBuilder.append(this.blank);
        stringBuilder.append(")?");
        stringBuilder.append(this.city);
        stringBuilder.append("(");
        stringBuilder.append(this.blank);
        stringBuilder.append(this.code);
        stringBuilder.append(")?");
        stringBuilder.append(")?");
        this.s52_sub = stringBuilder.toString();
        this.p52_sub = Pattern.compile(this.s52_sub);
    }
}
